/**
 * SAVORIA RESTAURANT - COMPREHENSIVE MENU DATABASE
 * 55+ Premium Menu Items across 8 Categories
 * Includes: nutritional info, allergens, preparation time, ratings
 */

const menuItems = [
    // ==================== STARTERS (10 items) ====================
    {
        id: 1,
        name: "Truffle Mushroom Crostini",
        category: "Starters",
        price: 395,
        description: "Crispy sourdough topped with wild mushroom ragout and truffle oil drizzle.",
        image: "https://images.unsplash.com/photo-1541014741259-de529411b96a?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "gourmet", "chef-special"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 15,
        rating: 4.8,
        ratingCount: 234,
        calories: 280,
        allergens: ["gluten", "dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 2,
        name: "Chicken 65",
        category: "Starters",
        price: 345,
        description: "Fiery Hyderabadi-style fried chicken with curry leaves and red chilies.",
        image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "spicy", "popular"],
        isVeg: false,
        spiceLevel: 3,
        prepTime: 20,
        rating: 4.7,
        ratingCount: 567,
        calories: 420,
        allergens: [],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 3,
        name: "Paneer Tikka",
        category: "Starters",
        price: 320,
        description: "Chargrilled cottage cheese cubes marinated in tandoori spices.",
        image: "https://images.unsplash.com/photo-1567184109411-b28f117c8f2b?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "tandoor", "bestseller"],
        isVeg: true,
        spiceLevel: 2,
        prepTime: 25,
        rating: 4.9,
        ratingCount: 892,
        calories: 350,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 4,
        name: "Crispy Corn Bites",
        category: "Starters",
        price: 225,
        description: "Golden-fried corn kernels tossed with garlic, chili, and spring onions.",
        image: "https://images.unsplash.com/photo-1551754655-cd27e38d2076?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "crunchy", "budget"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 12,
        rating: 4.5,
        ratingCount: 445,
        calories: 290,
        allergens: ["gluten"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 5,
        name: "Seekh Kebab",
        category: "Starters",
        price: 425,
        description: "Minced lamb skewers infused with aromatic spices, grilled to perfection.",
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "grill", "premium"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 30,
        rating: 4.8,
        ratingCount: 312,
        calories: 380,
        allergens: [],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 6,
        name: "Dahi Kebab",
        category: "Starters",
        price: 295,
        description: "Melt-in-mouth hung curd patties with cashew and raisin filling.",
        image: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "soft", "mild"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 20,
        rating: 4.6,
        ratingCount: 198,
        calories: 260,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 7,
        name: "Prawn Koliwada",
        category: "Starters",
        price: 545,
        description: "Mumbai-style battered prawns with authentic Koliwada masala.",
        image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "seafood", "mumbai-special"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 18,
        rating: 4.9,
        ratingCount: 287,
        calories: 340,
        allergens: ["shellfish", "gluten"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 8,
        name: "Hara Bhara Kebab",
        category: "Starters",
        price: 265,
        description: "Spinach and green pea patties with cottage cheese, lightly pan-fried.",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "healthy", "green"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 15,
        rating: 4.4,
        ratingCount: 356,
        calories: 220,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 9,
        name: "Chicken Malai Tikka",
        category: "Starters",
        price: 395,
        description: "Creamy, mildly spiced chicken tikka with cashew and cream marinade.",
        image: "https://images.unsplash.com/photo-1628294896516-344152572ee8?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "mild", "creamy"],
        isVeg: false,
        spiceLevel: 1,
        prepTime: 25,
        rating: 4.7,
        ratingCount: 423,
        calories: 380,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 10,
        name: "Spring Roll Platter",
        category: "Starters",
        price: 275,
        description: "Crispy vegetable spring rolls served with sweet chili and plum sauce.",
        image: "https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "chinese", "crunchy"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 15,
        rating: 4.3,
        ratingCount: 289,
        calories: 320,
        allergens: ["gluten", "soy"],
        isAvailable: true,
        isBestseller: false
    },

    // ==================== MAIN COURSE (12 items) ====================
    {
        id: 11,
        name: "Butter Chicken",
        category: "Main Course",
        price: 450,
        description: "Iconic Delhi-style tender chicken in silky tomato-fenugreek gravy.",
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "mild", "iconic"],
        isVeg: false,
        spiceLevel: 1,
        prepTime: 30,
        rating: 4.9,
        ratingCount: 1245,
        calories: 520,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 12,
        name: "Dal Makhani",
        category: "Main Course",
        price: 295,
        description: "24-hour slow-cooked black lentils enriched with cream and butter.",
        image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "signature", "slow-cooked"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 20,
        rating: 4.8,
        ratingCount: 987,
        calories: 380,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 13,
        name: "Lamb Rogan Josh",
        category: "Main Course",
        price: 595,
        description: "Kashmiri-style aromatic lamb curry with Kashmiri red chili.",
        image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "kashmiri", "premium"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 45,
        rating: 4.8,
        ratingCount: 456,
        calories: 580,
        allergens: [],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 14,
        name: "Paneer Lababdar",
        category: "Main Course",
        price: 345,
        description: "Cottage cheese cubes in rich, creamy tomato and cashew gravy.",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "rich", "creamy"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 25,
        rating: 4.7,
        ratingCount: 534,
        calories: 420,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 15,
        name: "Chicken Chettinad",
        category: "Main Course",
        price: 425,
        description: "Fiery South Indian chicken preparation with black pepper and fennel.",
        image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "spicy", "south-indian"],
        isVeg: false,
        spiceLevel: 3,
        prepTime: 35,
        rating: 4.6,
        ratingCount: 378,
        calories: 450,
        allergens: [],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 16,
        name: "Palak Paneer",
        category: "Main Course",
        price: 315,
        description: "Fresh spinach puree with soft paneer cubes and aromatic spices.",
        image: "https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "healthy", "iron-rich"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 25,
        rating: 4.5,
        ratingCount: 645,
        calories: 340,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 17,
        name: "Fish Curry (Coastal)",
        category: "Main Course",
        price: 495,
        description: "Fresh pomfret in tangy Konkan-style coconut curry.",
        image: "https://images.unsplash.com/photo-1539136788836-5699e78bfc75?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "seafood", "coastal"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 30,
        rating: 4.7,
        ratingCount: 234,
        calories: 380,
        allergens: ["fish", "coconut"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 18,
        name: "Kadai Paneer",
        category: "Main Course",
        price: 335,
        description: "Paneer and bell peppers in aromatic kadai masala with fresh coriander.",
        image: "https://images.unsplash.com/photo-1627662168223-7df99068099a?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "spicy", "kadai"],
        isVeg: true,
        spiceLevel: 2,
        prepTime: 20,
        rating: 4.6,
        ratingCount: 467,
        calories: 390,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 19,
        name: "Mutton Biryani",
        category: "Main Course",
        price: 545,
        description: "Lucknowi-style dum biryani with tender mutton and fragrant basmati.",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "biryani", "dum"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 50,
        rating: 4.9,
        ratingCount: 876,
        calories: 680,
        allergens: [],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 20,
        name: "Mushroom Masala",
        category: "Main Course",
        price: 295,
        description: "Button mushrooms in rich, spiced onion-tomato gravy.",
        image: "https://images.unsplash.com/photo-1606923829579-0cb981a83e2e?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "mushroom", "masala"],
        isVeg: true,
        spiceLevel: 2,
        prepTime: 20,
        rating: 4.4,
        ratingCount: 312,
        calories: 280,
        allergens: [],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 21,
        name: "Chicken Tikka Masala",
        category: "Main Course",
        price: 445,
        description: "Tandoor-grilled chicken tikka finished in creamy tomato masala.",
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "popular", "creamy"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 35,
        rating: 4.8,
        ratingCount: 723,
        calories: 490,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 22,
        name: "Mixed Vegetable Korma",
        category: "Main Course",
        price: 285,
        description: "Garden vegetables in mild, creamy cashew and almond gravy.",
        image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "mild", "kids-friendly"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 25,
        rating: 4.3,
        ratingCount: 234,
        calories: 320,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: false
    },

    // ==================== BREADS (6 items) ====================
    {
        id: 23,
        name: "Butter Naan",
        category: "Breads",
        price: 65,
        description: "Soft, fluffy tandoor-baked bread brushed with melted butter.",
        image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "tandoor", "essential"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 8,
        rating: 4.6,
        ratingCount: 1567,
        calories: 180,
        allergens: ["gluten", "dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 24,
        name: "Garlic Naan",
        category: "Breads",
        price: 85,
        description: "Naan topped with fresh garlic and coriander.",
        image: "https://images.unsplash.com/photo-1584736286279-65998c0a5f4b?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "garlic", "popular"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 8,
        rating: 4.7,
        ratingCount: 1234,
        calories: 195,
        allergens: ["gluten", "dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 25,
        name: "Stuffed Kulcha",
        category: "Breads",
        price: 95,
        description: "Naan stuffed with spiced potato or paneer filling.",
        image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "stuffed", "filling"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 12,
        rating: 4.5,
        ratingCount: 567,
        calories: 280,
        allergens: ["gluten", "dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 26,
        name: "Laccha Paratha",
        category: "Breads",
        price: 75,
        description: "Flaky, layered whole wheat bread with crispy edges.",
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "flaky", "traditional"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 10,
        rating: 4.4,
        ratingCount: 445,
        calories: 220,
        allergens: ["gluten", "dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 27,
        name: "Tandoori Roti",
        category: "Breads",
        price: 45,
        description: "Healthy whole wheat bread baked in traditional clay oven.",
        image: "https://images.unsplash.com/photo-1574484284002-952d92456975?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "healthy", "budget"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 6,
        rating: 4.3,
        ratingCount: 789,
        calories: 120,
        allergens: ["gluten"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 28,
        name: "Cheese Naan",
        category: "Breads",
        price: 125,
        description: "Naan stuffed with melting mozzarella and cheddar cheese.",
        image: "https://images.unsplash.com/photo-1619531040576-f9416740661b?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "cheese", "indulgent"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 10,
        rating: 4.8,
        ratingCount: 678,
        calories: 350,
        allergens: ["gluten", "dairy"],
        isAvailable: true,
        isBestseller: true
    },

    // ==================== RICE & BIRYANI (6 items) ====================
    {
        id: 29,
        name: "Hyderabadi Chicken Biryani",
        category: "Rice & Biryani",
        price: 395,
        description: "Aromatic basmati rice layered with spiced chicken, slow-cooked dum style.",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "biryani", "signature"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 45,
        rating: 4.9,
        ratingCount: 1456,
        calories: 620,
        allergens: [],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 30,
        name: "Vegetable Biryani",
        category: "Rice & Biryani",
        price: 295,
        description: "Fragrant basmati rice cooked with seasonal vegetables and whole spices.",
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "biryani", "aromatic"],
        isVeg: true,
        spiceLevel: 2,
        prepTime: 40,
        rating: 4.5,
        ratingCount: 567,
        calories: 480,
        allergens: [],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 31,
        name: "Jeera Rice",
        category: "Rice & Biryani",
        price: 165,
        description: "Basmati rice tempered with cumin seeds and ghee.",
        image: "https://images.unsplash.com/photo-1596097635121-14b63b7bbdc3?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "simple", "essential"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 15,
        rating: 4.4,
        ratingCount: 890,
        calories: 280,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 32,
        name: "Prawn Biryani",
        category: "Rice & Biryani",
        price: 545,
        description: "Coastal-style biryani with jumbo prawns and aromatic spices.",
        image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "seafood", "premium"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 45,
        rating: 4.7,
        ratingCount: 234,
        calories: 550,
        allergens: ["shellfish"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 33,
        name: "Kashmiri Pulao",
        category: "Rice & Biryani",
        price: 245,
        description: "Sweet and aromatic rice with dry fruits, saffron, and mild spices.",
        image: "https://images.unsplash.com/photo-1596097635121-14b63b7bbdc3?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "sweet", "kashmiri"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 25,
        rating: 4.5,
        ratingCount: 345,
        calories: 380,
        allergens: ["nuts", "dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 34,
        name: "Egg Fried Rice",
        category: "Rice & Biryani",
        price: 225,
        description: "Wok-tossed rice with scrambled eggs, vegetables, and soy.",
        image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=400&q=80",
        tags: ["egg", "chinese", "quick"],
        isVeg: false,
        spiceLevel: 1,
        prepTime: 15,
        rating: 4.4,
        ratingCount: 567,
        calories: 420,
        allergens: ["egg", "soy"],
        isAvailable: true,
        isBestseller: false
    },

    // ==================== DESSERTS (8 items) ====================
    {
        id: 35,
        name: "Gulab Jamun",
        category: "Desserts",
        price: 165,
        description: "Soft milk dumplings soaked in warm rose and cardamom syrup.",
        image: "https://images.unsplash.com/photo-1589119908995-c6837fa14848?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "sweet", "classic"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 10,
        rating: 4.7,
        ratingCount: 1234,
        calories: 420,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 36,
        name: "Rasmalai",
        category: "Desserts",
        price: 195,
        description: "Soft paneer discs in saffron and cardamom-infused milk.",
        image: "https://images.unsplash.com/photo-1604598616867-89ffd6e1c8cf?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "bengali", "premium"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 8,
        rating: 4.8,
        ratingCount: 876,
        calories: 380,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 37,
        name: "Kulfi Falooda",
        category: "Desserts",
        price: 225,
        description: "Traditional Indian ice cream with vermicelli, basil seeds, and rose syrup.",
        image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "cold", "refreshing"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 10,
        rating: 4.6,
        ratingCount: 567,
        calories: 450,
        allergens: ["dairy", "gluten"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 38,
        name: "Gajar Ka Halwa",
        category: "Desserts",
        price: 175,
        description: "Slow-cooked carrot pudding with khoya and dry fruits.",
        image: "https://images.unsplash.com/photo-1576069768127-ed1b2a7f0d7b?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "winter-special", "traditional"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 12,
        rating: 4.7,
        ratingCount: 678,
        calories: 380,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 39,
        name: "Chocolate Brownie with Ice Cream",
        category: "Desserts",
        price: 245,
        description: "Warm, gooey chocolate brownie served with vanilla ice cream.",
        image: "https://images.unsplash.com/photo-1564355808539-22fda35bed7e?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "chocolate", "indulgent"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 8,
        rating: 4.8,
        ratingCount: 789,
        calories: 520,
        allergens: ["dairy", "gluten", "eggs"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 40,
        name: "Mango Shrikhand",
        category: "Desserts",
        price: 165,
        description: "Creamy hung-curd dessert with Alphonso mango pulp.",
        image: "https://images.unsplash.com/photo-1565958011703-44f9829ba187?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "seasonal", "mango"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 5,
        rating: 4.6,
        ratingCount: 456,
        calories: 320,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 41,
        name: "Jalebi with Rabri",
        category: "Desserts",
        price: 185,
        description: "Crispy, syrup-soaked spirals served with thick, creamy rabri.",
        image: "https://images.unsplash.com/photo-1601050690117-94f5f7fa752a?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "classic", "festive"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 10,
        rating: 4.5,
        ratingCount: 567,
        calories: 480,
        allergens: ["dairy", "gluten"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 42,
        name: "Phirni",
        category: "Desserts",
        price: 145,
        description: "Ground rice pudding set in earthen pots, topped with pistachios.",
        image: "https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "mughlai", "light"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 8,
        rating: 4.4,
        ratingCount: 345,
        calories: 280,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: false
    },

    // ==================== BEVERAGES (8 items) ====================
    {
        id: 43,
        name: "Masala Chai",
        category: "Beverages",
        price: 65,
        description: "Traditional Indian spiced tea with ginger and cardamom.",
        image: "https://images.unsplash.com/photo-1597318181409-cf64d0b5d8a2?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "hot", "traditional"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 5,
        rating: 4.6,
        ratingCount: 1456,
        calories: 80,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 44,
        name: "Mango Lassi",
        category: "Beverages",
        price: 125,
        description: "Creamy yogurt smoothie blended with fresh Alphonso mango.",
        image: "https://images.unsplash.com/photo-1570695396449-47df2f9a4c37?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "cold", "refreshing"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 5,
        rating: 4.7,
        ratingCount: 987,
        calories: 220,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 45,
        name: "Fresh Lime Soda",
        category: "Beverages",
        price: 85,
        description: "Refreshing lime juice with soda, available sweet or salted.",
        image: "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "cold", "refreshing"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 3,
        rating: 4.4,
        ratingCount: 678,
        calories: 60,
        allergens: [],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 46,
        name: "Rose Sharbat",
        category: "Beverages",
        price: 95,
        description: "Chilled rose-flavored drink with basil seeds.",
        image: "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "cold", "floral"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 3,
        rating: 4.5,
        ratingCount: 456,
        calories: 120,
        allergens: [],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 47,
        name: "Cold Coffee",
        category: "Beverages",
        price: 145,
        description: "Creamy iced coffee with vanilla ice cream.",
        image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "cold", "caffeine"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 5,
        rating: 4.6,
        ratingCount: 567,
        calories: 280,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 48,
        name: "Jaljeera",
        category: "Beverages",
        price: 75,
        description: "Tangy cumin-mint cooler, perfect digestive drink.",
        image: "https://images.unsplash.com/photo-1534353473418-4cfa6c56fd38?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "digestive", "tangy"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 3,
        rating: 4.3,
        ratingCount: 345,
        calories: 40,
        allergens: [],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 49,
        name: "Buttermilk (Chaas)",
        category: "Beverages",
        price: 55,
        description: "Spiced buttermilk with cumin, coriander, and mint.",
        image: "https://images.unsplash.com/photo-1570695396449-47df2f9a4c37?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "cooling", "healthy"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 3,
        rating: 4.5,
        ratingCount: 567,
        calories: 50,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 50,
        name: "Thandai",
        category: "Beverages",
        price: 145,
        description: "Traditional festive drink with almonds, fennel, and rose petals.",
        image: "https://images.unsplash.com/photo-1497534446932-c925b458314e?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "festive", "nutty"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 5,
        rating: 4.7,
        ratingCount: 456,
        calories: 280,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: false
    },

    // ==================== CHEF'S SPECIALS (5 items) ====================
    {
        id: 51,
        name: "Truffle Butter Chicken",
        category: "Chef's Specials",
        price: 695,
        description: "Our signature butter chicken elevated with black truffle oil.",
        image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "luxury", "signature"],
        isVeg: false,
        spiceLevel: 1,
        prepTime: 40,
        rating: 4.9,
        ratingCount: 234,
        calories: 580,
        allergens: ["dairy"],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 52,
        name: "Lobster Thermidor",
        category: "Chef's Specials",
        price: 1495,
        description: "Whole lobster in creamy mustard sauce, gratinated to perfection.",
        image: "https://images.unsplash.com/photo-1565680018434-b513d5e5fd47?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "premium", "seafood"],
        isVeg: false,
        spiceLevel: 1,
        prepTime: 45,
        rating: 4.9,
        ratingCount: 89,
        calories: 520,
        allergens: ["shellfish", "dairy"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 53,
        name: "Molecular Rasmalai",
        category: "Chef's Specials",
        price: 395,
        description: "Deconstructed rasmalai with saffron foam and pistachio crumble.",
        image: "https://images.unsplash.com/photo-1604598616867-89ffd6e1c8cf?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "molecular", "artistic"],
        isVeg: true,
        spiceLevel: 0,
        prepTime: 15,
        rating: 4.8,
        ratingCount: 167,
        calories: 320,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: false
    },
    {
        id: 54,
        name: "Wagyu Seekh Kebab",
        category: "Chef's Specials",
        price: 895,
        description: "Premium Japanese Wagyu beef seekh with truffle aioli.",
        image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?auto=format&fit=crop&w=400&q=80",
        tags: ["non-veg", "wagyu", "premium"],
        isVeg: false,
        spiceLevel: 2,
        prepTime: 35,
        rating: 4.9,
        ratingCount: 123,
        calories: 450,
        allergens: [],
        isAvailable: true,
        isBestseller: true
    },
    {
        id: 55,
        name: "Saffron Paneer Royale",
        category: "Chef's Specials",
        price: 545,
        description: "Hand-churned paneer in Kashmiri saffron and dry fruit gravy.",
        image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?auto=format&fit=crop&w=400&q=80",
        tags: ["veg", "royal", "kashmiri"],
        isVeg: true,
        spiceLevel: 1,
        prepTime: 30,
        rating: 4.8,
        ratingCount: 198,
        calories: 480,
        allergens: ["dairy", "nuts"],
        isAvailable: true,
        isBestseller: true
    }
];

// Category summary for quick reference
const categories = [
    { id: 1, name: "Starters", icon: "🥗", itemCount: 10 },
    { id: 2, name: "Main Course", icon: "🍛", itemCount: 12 },
    { id: 3, name: "Breads", icon: "🫓", itemCount: 6 },
    { id: 4, name: "Rice & Biryani", icon: "🍚", itemCount: 6 },
    { id: 5, name: "Desserts", icon: "🍮", itemCount: 8 },
    { id: 6, name: "Beverages", icon: "🥤", itemCount: 8 },
    { id: 7, name: "Chef's Specials", icon: "👨‍🍳", itemCount: 5 }
];

// Export for Node.js / Backend use
module.exports = { menuItems, categories };
